export class Window {
    constructor(width: number, height: number, title: string);

    shouldClose: boolean;

    swapBuffers(): void;

    setKeyCallback(cb: (key: number, scancode: number, action: number, mods: number) => void | null): void;

    destroyWindow(): void;
}

export function pollEvents(): void;

export const TRUE: number;
export const FALSE: number;

export const RELEASE: number;
export const PRESS: number;
export const REPEAT: number;

export const HAT_CENTERED: number;
export const HAT_UP: number;
export const HAT_RIGHT: number;
export const HAT_DOWN: number;
export const HAT_LEFT: number;
export const HAT_RIGHT_UP: number;
export const HAT_RIGHT_DOWN: number;
export const HAT_LEFT_UP: number;
export const HAT_LEFT_DOWN: number;

/* Printable keys */
export const KEY_SPACE: number;
export const KEY_APOSTROPHE: number;
export const KEY_COMMA: number;
export const KEY_MINUS: number;
export const KEY_PERIOD: number;
export const KEY_SLASH: number;
export const KEY_0: number;
export const KEY_1: number;
export const KEY_2: number;
export const KEY_3: number;
export const KEY_4: number;
export const KEY_5: number;
export const KEY_6: number;
export const KEY_7: number;
export const KEY_8: number;
export const KEY_9: number;
export const KEY_SEMICOLON: number;
export const KEY_EQUAL: number;
export const KEY_A: number;
export const KEY_B: number;
export const KEY_C: number;
export const KEY_D: number;
export const KEY_E: number;
export const KEY_F: number;
export const KEY_G: number;
export const KEY_H: number;
export const KEY_I: number;
export const KEY_J: number;
export const KEY_K: number;
export const KEY_L: number;
export const KEY_M: number;
export const KEY_N: number;
export const KEY_O: number;
export const KEY_P: number;
export const KEY_Q: number;
export const KEY_R: number;
export const KEY_S: number;
export const KEY_T: number;
export const KEY_U: number;
export const KEY_V: number;
export const KEY_W: number;
export const KEY_X: number;
export const KEY_Y: number;
export const KEY_Z: number;
export const KEY_LEFT_BRACKET: number;
export const KEY_BACKSLASH: number;
export const KEY_RIGHT_BRACKET: number;
export const KEY_GRAVE_ACCENT: number;
export const KEY_WORLD_1: number;
export const KEY_WORLD_2: number;

/* Function keys */
export const KEY_ESCAPE: number;
export const KEY_ENTER: number;
export const KEY_TAB: number;
export const KEY_BACKSPACE: number;
export const KEY_INSERT: number;
export const KEY_DELETE: number;
export const KEY_RIGHT: number;
export const KEY_LEFT: number;
export const KEY_DOWN: number;
export const KEY_UP: number;
export const KEY_PAGE_UP: number;
export const KEY_PAGE_DOWN: number;
export const KEY_HOME: number;
export const KEY_END: number;
export const KEY_CAPS_LOCK: number;
export const KEY_SCROLL_LOCK: number;
export const KEY_NUM_LOCK: number;
export const KEY_PRINT_SCREEN: number;
export const KEY_PAUSE: number;
export const KEY_F1: number;
export const KEY_F2: number;
export const KEY_F3: number;
export const KEY_F4: number;
export const KEY_F5: number;
export const KEY_F6: number;
export const KEY_F7: number;
export const KEY_F8: number;
export const KEY_F9: number;
export const KEY_F10: number;
export const KEY_F11: number;
export const KEY_F12: number;
export const KEY_F13: number;
export const KEY_F14: number;
export const KEY_F15: number;
export const KEY_F16: number;
export const KEY_F17: number;
export const KEY_F18: number;
export const KEY_F19: number;
export const KEY_F20: number;
export const KEY_F21: number;
export const KEY_F22: number;
export const KEY_F23: number;
export const KEY_F24: number;
export const KEY_F25: number;
export const KEY_KP_0: number;
export const KEY_KP_1: number;
export const KEY_KP_2: number;
export const KEY_KP_3: number;
export const KEY_KP_4: number;
export const KEY_KP_5: number;
export const KEY_KP_6: number;
export const KEY_KP_7: number;
export const KEY_KP_8: number;
export const KEY_KP_9: number;
export const KEY_KP_DECIMAL: number;
export const KEY_KP_DIVIDE: number;
export const KEY_KP_MULTIPLY: number;
export const KEY_KP_SUBTRACT: number;
export const KEY_KP_ADD: number;
export const KEY_KP_ENTER: number;
export const KEY_KP_EQUAL: number;
export const KEY_LEFT_SHIFT: number;
export const KEY_LEFT_CONTROL: number;
export const KEY_LEFT_ALT: number;
export const KEY_LEFT_SUPER: number;
export const KEY_RIGHT_SHIFT: number;
export const KEY_RIGHT_CONTROL: number;
export const KEY_RIGHT_ALT: number;
export const KEY_RIGHT_SUPER: number;
export const KEY_MENU: number;

export const KEY_LAST: number;

export const MOD_SHIFT: number;
export const MOD_CONTROL: number;
export const MOD_ALT: number;
export const MOD_SUPER: number;
export const MOD_CAPS_LOCK: number;
export const MOD_NUM_LOCK: number;

export const MOUSE_BUTTON_1: number;
export const MOUSE_BUTTON_2: number;
export const MOUSE_BUTTON_3: number;
export const MOUSE_BUTTON_4: number;
export const MOUSE_BUTTON_5: number;
export const MOUSE_BUTTON_6: number;
export const MOUSE_BUTTON_7: number;
export const MOUSE_BUTTON_8: number;
export const MOUSE_BUTTON_LAST: number;
export const MOUSE_BUTTON_LEFT: number;
export const MOUSE_BUTTON_RIGHT: number;
export const MOUSE_BUTTON_MIDDLE: number;

export const JOYSTICK_1: number;
export const JOYSTICK_2: number;
export const JOYSTICK_3: number;
export const JOYSTICK_4: number;
export const JOYSTICK_5: number;
export const JOYSTICK_6: number;
export const JOYSTICK_7: number;
export const JOYSTICK_8: number;
export const JOYSTICK_9: number;
export const JOYSTICK_10: number;
export const JOYSTICK_11: number;
export const JOYSTICK_12: number;
export const JOYSTICK_13: number;
export const JOYSTICK_14: number;
export const JOYSTICK_15: number;
export const JOYSTICK_16: number;
export const JOYSTICK_LAST: number;

export const GAMEPAD_BUTTON_A: number;
export const GAMEPAD_BUTTON_B: number;
export const GAMEPAD_BUTTON_X: number;
export const GAMEPAD_BUTTON_Y: number;
export const GAMEPAD_BUTTON_LEFT_BUMPER: number;
export const GAMEPAD_BUTTON_RIGHT_BUMPER: number;
export const GAMEPAD_BUTTON_BACK: number;
export const GAMEPAD_BUTTON_START: number;
export const GAMEPAD_BUTTON_GUIDE: number;
export const GAMEPAD_BUTTON_LEFT_THUMB: number;
export const GAMEPAD_BUTTON_RIGHT_THUMB: number;
export const GAMEPAD_BUTTON_DPAD_UP: number;
export const GAMEPAD_BUTTON_DPAD_RIGHT: number;
export const GAMEPAD_BUTTON_DPAD_DOWN: number;
export const GAMEPAD_BUTTON_DPAD_LEFT: number;
export const GAMEPAD_BUTTON_LAST: number;

export const GAMEPAD_BUTTON_CROSS: number;
export const GAMEPAD_BUTTON_CIRCLE: number;
export const GAMEPAD_BUTTON_SQUARE: number;
export const GAMEPAD_BUTTON_TRIANGLE: number;

export const GAMEPAD_AXIS_LEFT_X: number;
export const GAMEPAD_AXIS_LEFT_Y: number;
export const GAMEPAD_AXIS_RIGHT_X: number;
export const GAMEPAD_AXIS_RIGHT_Y: number;
export const GAMEPAD_AXIS_LEFT_TRIGGER: number;
export const GAMEPAD_AXIS_RIGHT_TRIGGER: number;
export const GAMEPAD_AXIS_LAST: number;
