#include <GLFW/glfw3.h>
#include <napi.h>

using Napi::Number;
using Napi::PropertyDescriptor;

#define ConstantDescriptor(name) \
    PropertyDescriptor::Value(#name, Number::New(env, GLFW_##name), napi_enumerable)

void InitConstants(Napi::Env env, Napi::Object exports)
{
    exports.DefineProperties({
        ConstantDescriptor(TRUE),
        ConstantDescriptor(FALSE),

        ConstantDescriptor(RELEASE),
        ConstantDescriptor(PRESS),
        ConstantDescriptor(REPEAT),

        ConstantDescriptor(HAT_CENTERED),
        ConstantDescriptor(HAT_UP),
        ConstantDescriptor(HAT_RIGHT),
        ConstantDescriptor(HAT_DOWN),
        ConstantDescriptor(HAT_LEFT),
        ConstantDescriptor(HAT_RIGHT_UP),
        ConstantDescriptor(HAT_RIGHT_DOWN),
        ConstantDescriptor(HAT_LEFT_UP),
        ConstantDescriptor(HAT_LEFT_DOWN),

        /* Printable keys */
        ConstantDescriptor(KEY_SPACE),
        ConstantDescriptor(KEY_APOSTROPHE),
        ConstantDescriptor(KEY_COMMA),
        ConstantDescriptor(KEY_MINUS),
        ConstantDescriptor(KEY_PERIOD),
        ConstantDescriptor(KEY_SLASH),
        ConstantDescriptor(KEY_0),
        ConstantDescriptor(KEY_1),
        ConstantDescriptor(KEY_2),
        ConstantDescriptor(KEY_3),
        ConstantDescriptor(KEY_4),
        ConstantDescriptor(KEY_5),
        ConstantDescriptor(KEY_6),
        ConstantDescriptor(KEY_7),
        ConstantDescriptor(KEY_8),
        ConstantDescriptor(KEY_9),
        ConstantDescriptor(KEY_SEMICOLON),
        ConstantDescriptor(KEY_EQUAL),
        ConstantDescriptor(KEY_A),
        ConstantDescriptor(KEY_B),
        ConstantDescriptor(KEY_C),
        ConstantDescriptor(KEY_D),
        ConstantDescriptor(KEY_E),
        ConstantDescriptor(KEY_F),
        ConstantDescriptor(KEY_G),
        ConstantDescriptor(KEY_H),
        ConstantDescriptor(KEY_I),
        ConstantDescriptor(KEY_J),
        ConstantDescriptor(KEY_K),
        ConstantDescriptor(KEY_L),
        ConstantDescriptor(KEY_M),
        ConstantDescriptor(KEY_N),
        ConstantDescriptor(KEY_O),
        ConstantDescriptor(KEY_P),
        ConstantDescriptor(KEY_Q),
        ConstantDescriptor(KEY_R),
        ConstantDescriptor(KEY_S),
        ConstantDescriptor(KEY_T),
        ConstantDescriptor(KEY_U),
        ConstantDescriptor(KEY_V),
        ConstantDescriptor(KEY_W),
        ConstantDescriptor(KEY_X),
        ConstantDescriptor(KEY_Y),
        ConstantDescriptor(KEY_Z),
        ConstantDescriptor(KEY_LEFT_BRACKET),
        ConstantDescriptor(KEY_BACKSLASH),
        ConstantDescriptor(KEY_RIGHT_BRACKET),
        ConstantDescriptor(KEY_GRAVE_ACCENT),
        ConstantDescriptor(KEY_WORLD_1),
        ConstantDescriptor(KEY_WORLD_2),

        /* Function keys */
        ConstantDescriptor(KEY_ESCAPE),
        ConstantDescriptor(KEY_ENTER),
        ConstantDescriptor(KEY_TAB),
        ConstantDescriptor(KEY_BACKSPACE),
        ConstantDescriptor(KEY_INSERT),
        ConstantDescriptor(KEY_DELETE),
        ConstantDescriptor(KEY_RIGHT),
        ConstantDescriptor(KEY_LEFT),
        ConstantDescriptor(KEY_DOWN),
        ConstantDescriptor(KEY_UP),
        ConstantDescriptor(KEY_PAGE_UP),
        ConstantDescriptor(KEY_PAGE_DOWN),
        ConstantDescriptor(KEY_HOME),
        ConstantDescriptor(KEY_END),
        ConstantDescriptor(KEY_CAPS_LOCK),
        ConstantDescriptor(KEY_SCROLL_LOCK),
        ConstantDescriptor(KEY_NUM_LOCK),
        ConstantDescriptor(KEY_PRINT_SCREEN),
        ConstantDescriptor(KEY_PAUSE),
        ConstantDescriptor(KEY_F1),
        ConstantDescriptor(KEY_F2),
        ConstantDescriptor(KEY_F3),
        ConstantDescriptor(KEY_F4),
        ConstantDescriptor(KEY_F5),
        ConstantDescriptor(KEY_F6),
        ConstantDescriptor(KEY_F7),
        ConstantDescriptor(KEY_F8),
        ConstantDescriptor(KEY_F9),
        ConstantDescriptor(KEY_F10),
        ConstantDescriptor(KEY_F11),
        ConstantDescriptor(KEY_F12),
        ConstantDescriptor(KEY_F13),
        ConstantDescriptor(KEY_F14),
        ConstantDescriptor(KEY_F15),
        ConstantDescriptor(KEY_F16),
        ConstantDescriptor(KEY_F17),
        ConstantDescriptor(KEY_F18),
        ConstantDescriptor(KEY_F19),
        ConstantDescriptor(KEY_F20),
        ConstantDescriptor(KEY_F21),
        ConstantDescriptor(KEY_F22),
        ConstantDescriptor(KEY_F23),
        ConstantDescriptor(KEY_F24),
        ConstantDescriptor(KEY_F25),
        ConstantDescriptor(KEY_KP_0),
        ConstantDescriptor(KEY_KP_1),
        ConstantDescriptor(KEY_KP_2),
        ConstantDescriptor(KEY_KP_3),
        ConstantDescriptor(KEY_KP_4),
        ConstantDescriptor(KEY_KP_5),
        ConstantDescriptor(KEY_KP_6),
        ConstantDescriptor(KEY_KP_7),
        ConstantDescriptor(KEY_KP_8),
        ConstantDescriptor(KEY_KP_9),
        ConstantDescriptor(KEY_KP_DECIMAL),
        ConstantDescriptor(KEY_KP_DIVIDE),
        ConstantDescriptor(KEY_KP_MULTIPLY),
        ConstantDescriptor(KEY_KP_SUBTRACT),
        ConstantDescriptor(KEY_KP_ADD),
        ConstantDescriptor(KEY_KP_ENTER),
        ConstantDescriptor(KEY_KP_EQUAL),
        ConstantDescriptor(KEY_LEFT_SHIFT),
        ConstantDescriptor(KEY_LEFT_CONTROL),
        ConstantDescriptor(KEY_LEFT_ALT),
        ConstantDescriptor(KEY_LEFT_SUPER),
        ConstantDescriptor(KEY_RIGHT_SHIFT),
        ConstantDescriptor(KEY_RIGHT_CONTROL),
        ConstantDescriptor(KEY_RIGHT_ALT),
        ConstantDescriptor(KEY_RIGHT_SUPER),
        ConstantDescriptor(KEY_MENU),

        ConstantDescriptor(KEY_LAST),

        ConstantDescriptor(MOD_SHIFT),
        ConstantDescriptor(MOD_CONTROL),
        ConstantDescriptor(MOD_ALT),
        ConstantDescriptor(MOD_SUPER),
        ConstantDescriptor(MOD_CAPS_LOCK),
        ConstantDescriptor(MOD_NUM_LOCK),

        ConstantDescriptor(MOUSE_BUTTON_1),
        ConstantDescriptor(MOUSE_BUTTON_2),
        ConstantDescriptor(MOUSE_BUTTON_3),
        ConstantDescriptor(MOUSE_BUTTON_4),
        ConstantDescriptor(MOUSE_BUTTON_5),
        ConstantDescriptor(MOUSE_BUTTON_6),
        ConstantDescriptor(MOUSE_BUTTON_7),
        ConstantDescriptor(MOUSE_BUTTON_8),
        ConstantDescriptor(MOUSE_BUTTON_LAST),
        ConstantDescriptor(MOUSE_BUTTON_LEFT),
        ConstantDescriptor(MOUSE_BUTTON_RIGHT),
        ConstantDescriptor(MOUSE_BUTTON_MIDDLE),

        ConstantDescriptor(JOYSTICK_1),
        ConstantDescriptor(JOYSTICK_2),
        ConstantDescriptor(JOYSTICK_3),
        ConstantDescriptor(JOYSTICK_4),
        ConstantDescriptor(JOYSTICK_5),
        ConstantDescriptor(JOYSTICK_6),
        ConstantDescriptor(JOYSTICK_7),
        ConstantDescriptor(JOYSTICK_8),
        ConstantDescriptor(JOYSTICK_9),
        ConstantDescriptor(JOYSTICK_10),
        ConstantDescriptor(JOYSTICK_11),
        ConstantDescriptor(JOYSTICK_12),
        ConstantDescriptor(JOYSTICK_13),
        ConstantDescriptor(JOYSTICK_14),
        ConstantDescriptor(JOYSTICK_15),
        ConstantDescriptor(JOYSTICK_16),
        ConstantDescriptor(JOYSTICK_LAST),

        ConstantDescriptor(GAMEPAD_BUTTON_A),
        ConstantDescriptor(GAMEPAD_BUTTON_B),
        ConstantDescriptor(GAMEPAD_BUTTON_X),
        ConstantDescriptor(GAMEPAD_BUTTON_Y),
        ConstantDescriptor(GAMEPAD_BUTTON_LEFT_BUMPER),
        ConstantDescriptor(GAMEPAD_BUTTON_RIGHT_BUMPER),
        ConstantDescriptor(GAMEPAD_BUTTON_BACK),
        ConstantDescriptor(GAMEPAD_BUTTON_START),
        ConstantDescriptor(GAMEPAD_BUTTON_GUIDE),
        ConstantDescriptor(GAMEPAD_BUTTON_LEFT_THUMB),
        ConstantDescriptor(GAMEPAD_BUTTON_RIGHT_THUMB),
        ConstantDescriptor(GAMEPAD_BUTTON_DPAD_UP),
        ConstantDescriptor(GAMEPAD_BUTTON_DPAD_RIGHT),
        ConstantDescriptor(GAMEPAD_BUTTON_DPAD_DOWN),
        ConstantDescriptor(GAMEPAD_BUTTON_DPAD_LEFT),
        ConstantDescriptor(GAMEPAD_BUTTON_LAST),

        ConstantDescriptor(GAMEPAD_BUTTON_CROSS),
        ConstantDescriptor(GAMEPAD_BUTTON_CIRCLE),
        ConstantDescriptor(GAMEPAD_BUTTON_SQUARE),
        ConstantDescriptor(GAMEPAD_BUTTON_TRIANGLE),

        ConstantDescriptor(GAMEPAD_AXIS_LEFT_X),
        ConstantDescriptor(GAMEPAD_AXIS_LEFT_Y),
        ConstantDescriptor(GAMEPAD_AXIS_RIGHT_X),
        ConstantDescriptor(GAMEPAD_AXIS_RIGHT_Y),
        ConstantDescriptor(GAMEPAD_AXIS_LEFT_TRIGGER),
        ConstantDescriptor(GAMEPAD_AXIS_RIGHT_TRIGGER),
        ConstantDescriptor(GAMEPAD_AXIS_LAST),
    });
}
