# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: sudo apt install xorg-dev
      - run: npm install
      - run: npm run setup && npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  build-debug-linux:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: sudo apt install xorg-dev
      - run: npm install
      - run: npm run setup && npm run build:debug
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  publish:
    needs: [build-release-linux, build-debug-linux]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      
      - run: npm install
      - run: npm pack
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./*.tgz
